// ─── Portfolio Content ────────────────────────────────────────────────────────
// Edit this file to add/remove/update projects.
//
// slug:        unique ID used in custom URLs (no spaces, lowercase, hyphens ok)
// tags:        used in the builder to group/filter projects for job applications
// client:      shown in the project modal (company or client name)
// year:        shown in the project modal
// description: shown in the project modal (right column)
// images:      number = cap on how many images from image-manifest.js to show
// captions:    optional array of strings, one per image in order (empty string = no caption)
// modal:       set to false to disable the modal for this project (default: true)
// ─────────────────────────────────────────────────────────────────────────────

const PROJECTS = [
  {
    order: 1,
    slug: 'qup',
    title: 'Q-UP',
    tags: ['game', 'design', 'branding', 'ui/ux', 'art direction', 'sound design'],
    role: 'Lead Designer',
    client: 'Everybody House Games',
    year: '2025',
    description: "Sick of long queues, unfair matchups, and arbitrary reflex tests? Try Q-UP, the coin flipping eSport. It's one part clicker, one part multiplayer strategy game, one part demented capitalism simulator, and 100% completely random.",
    captions: ['', '', '', '', '', '', '', ''],
    quote: '',
    images: 8,
    modal: false,
  },
  {
    order: 2,
    slug: 'netflix',
    title: 'Netflix',
    tags: ['campaign', 'interactive', 'ux'],
    role: 'Designer',
    client: 'Netflix',
    year: '',
    description: "Snow City is a digital experience created for Coach, exploring themes of winter, nostalgia, and urban exploration. The work drew on deep UX expertise to create something both brand-aligned and genuinely playful.",
    quote: "",
    images: 5,
    captions: ['', '', '', '', '', ''],
    modal:false,
  },
  {
    order: 8,
    slug: 'rewilding',
    title: 'Rewilding',
    tags: ['editorial', 'ux'],
    role: 'Designer',
    client: 'Personal',
    year: 'Ongoing',
    description: "a meditative ecology game about regrowing a forest as a means of reckoning with climate change and its effects.",
    quote: '',
    images: 6,
    modal: false,
  },
  {
    order: 7,
    slug: 'pokernight',
    title: 'Netflix Poker Night',
    tags: ['editorial', 'ux'],
    role: 'Designer',
    client: 'Personal',
    year: 'Ongoing',
    description: "a meditative ecology game about regrowing a forest as a means of reckoning with climate change and its effects.",
    quote: '',
    images: 6,
    modal: false,
  },
  {
    order: 6,
    slug: 'chrono',
    title: 'CHRONO',
    tags: ['editorial', 'ux'],
    role: 'Designer',
    client: 'Personal',
    year: 'Ongoing',
    description: "a meditative ecology game about regrowing a forest as a means of reckoning with climate change and its effects.",
    quote: '',
    images: 6,
    modal: false,
  },
  {
    order: 6,
    slug: 'multipuck',
    title: 'MULTIPUCK',
    tags: ['editorial', 'ux'],
    role: 'Designer',
    client: 'Personal',
    year: 'Ongoing',
    description: "a meditative ecology game about regrowing a forest as a means of reckoning with climate change and its effects.",
    quote: '',
    images: 5,
    modal: false,
  },
  {
    order: 7,
    slug: 'noclip',
    title: 'noclip',
    tags: ['sponsored', 'ux'],
    role: 'Motion Designer',
    client: 'Adobe',
    year: '',
    description: 'A sponsored collaboration with Adobe, distributed through Spotify, exploring the creative process and the intersection of design and technology.',
    quote: '',
    images: 6,
    modal: false,
  },
  {
    order: 3,
    slug: 'snowcity',
    title: 'Coach Snow City',
    tags: ['editorial', 'ux'],
    role: 'Lead Designer',
    client: 'Coach',
    year: '',
    description: 'Work featured in Wired magazine across stories on rewilding, climate change, and the gig economy — a visual and interactive contribution to reporting at the edge of technology and the natural world.',
    quote: '',
    images: 6,
    modal: false,
  },
  {
    order: 4,
    slug: 'coach',
    title: 'Coach',
    tags: ['editorial', 'ux'],
    role: 'UX & Interactive Designer',
    client: 'Coach',
    year: '',
    description: 'Work featured in Wired magazine across stories on rewilding, climate change, and the gig economy — a visual and interactive contribution to reporting at the edge of technology and the natural world.',
    quote: '',
    images: 6,
    modal: false,
  },
  {
    order: 5,
    slug: 'linkedin',
    title: 'LinkedIn Data Communities',
    tags: ['editorial', 'ux'],
    role: 'Interactive Designer',
    client: 'LinkedIn',
    year: '',
    description: 'A sponsored collaboration with Adobe, distributed through Spotify, exploring the creative process and the intersection of design and technology.',
    quote: '',
    images: 4,
    modal: false,
  },
  {
    order: 11,
    slug: 'megaware',
    title: 'MegaWare',
    tags: ['editorial', 'ux'],
    role: 'Designer',
    client: 'Personal',
    year: 'Ongoing',
    description: '',
    quote: '',
    images: 4,
    modal: false,
  },
];
