// Run with: node generate.js
// Scans images/<slug>/ for strip images and images/<slug>/modal/ for modal images.
// Writes image-manifest.js with { strip: [...], modal: [...] } per project.
//
// Modal image layout (naming convention):
//   01.jpg         → half-width (2 per row, default)
//   02_full.jpg    → full-width (spans entire modal)
//   03_full.webm   → full-width video (pair with 03_full-poster.jpg for thumbnail)

const fs   = require('fs');
const path = require('path');

const EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif', '.webm']);

// Pull slugs + image caps from data.js without eval
const dataRaw = fs.readFileSync('data.js', 'utf8');
const slugMatches   = [...dataRaw.matchAll(/slug:\s*['"]([^'"]+)['"]/g)];
const imagesMatches = [...dataRaw.matchAll(/images:\s*(\d+)/g)];

const projects = slugMatches.map((m, i) => ({
  slug: m[1],
  cap:  imagesMatches[i] ? parseInt(imagesMatches[i][1], 10) : Infinity,
}));

const numericSort = (a, b) => {
  const nA = parseInt(a.match(/^(\d+)/)?.[1] ?? '0', 10);
  const nB = parseInt(b.match(/^(\d+)/)?.[1] ?? '0', 10);
  return nA !== nB ? nA - nB : a.localeCompare(b);
};

function scanDir(dir, cap) {
  if (!fs.existsSync(dir)) return [];
  const allFiles = fs.readdirSync(dir)
    .filter(f => {
      const full = path.join(dir, f);
      return fs.statSync(full).isFile() && EXTENSIONS.has(path.extname(f).toLowerCase());
    })
    .sort(numericSort);

  const posterFiles = new Set(allFiles.filter(f => path.basename(f, path.extname(f)).endsWith('-poster')));

  return allFiles
    .filter(f => !posterFiles.has(f))
    .slice(0, cap)
    .map(f => {
      const base  = path.basename(f, path.extname(f));
      const mtime = fs.statSync(path.join(dir, f)).mtimeMs;
      const v     = `?v=${Math.floor(mtime)}`;
      if (path.extname(f).toLowerCase() === '.webm') {
        const posterFile = [...posterFiles].find(p => path.basename(p, path.extname(p)) === `${base}-poster`);
        if (posterFile) {
          const pmtime = fs.statSync(path.join(dir, posterFile)).mtimeMs;
          return { src: `${dir}/${f}${v}`, poster: `${dir}/${posterFile}?v=${Math.floor(pmtime)}` };
        }
        return { src: `${dir}/${f}${v}` };
      }
      return `${dir}/${f}${v}`;
    });
}

const manifest = {};

for (const { slug, cap } of projects) {
  const stripDir = path.join('images', slug);
  const modalDir = path.join('images', slug, 'modal');

  const strip = scanDir(stripDir, cap);
  const modal = scanDir(modalDir, Infinity);

  manifest[slug] = { strip, modal };
  console.log(`  ${slug}: ${strip.length} strip, ${modal.length} modal`);
}

const output =
  `// Auto-generated by generate.js — do not edit manually\n` +
  `// Run "node generate.js" any time you add or remove images\n` +
  `// Each entry: { strip: [...], modal: [...] }\n` +
  `// Drop images in images/<slug>/modal/ to show different images in the project popup\n` +
  `const IMAGE_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`;

fs.writeFileSync('image-manifest.js', output);
console.log('\n✓ image-manifest.js updated');
