// Run with: node generate.js
// Scans images/<slug>/ for each project and writes image-manifest.js

const fs   = require('fs');
const path = require('path');

const EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif', '.webm']);

// Pull slugs + image caps from data.js without eval
const dataRaw = fs.readFileSync('data.js', 'utf8');
const slugMatches   = [...dataRaw.matchAll(/slug:\s*['"]([^'"]+)['"]/g)];
const imagesMatches = [...dataRaw.matchAll(/images:\s*(\d+)/g)];

const projects = slugMatches.map((m, i) => ({
  slug: m[1],
  cap:  imagesMatches[i] ? parseInt(imagesMatches[i][1], 10) : Infinity,
}));

const manifest = {};

for (const { slug, cap } of projects) {
  const dir = path.join('images', slug);
  if (!fs.existsSync(dir)) {
    manifest[slug] = [];
    continue;
  }
  const numericSort = (a, b) => {
    const nA = parseInt(a.match(/^(\d+)/)?.[1] ?? '0', 10);
    const nB = parseInt(b.match(/^(\d+)/)?.[1] ?? '0', 10);
    return nA !== nB ? nA - nB : a.localeCompare(b);
  };
  const allFiles = fs.readdirSync(dir).filter(f => EXTENSIONS.has(path.extname(f).toLowerCase())).sort(numericSort);

  // Poster files (named like "01-poster.jpg") are attached to their video, not listed standalone
  const posterFiles = new Set(allFiles.filter(f => path.basename(f, path.extname(f)).endsWith('-poster')));

  const items = allFiles
    .filter(f => !posterFiles.has(f))
    .slice(0, cap)
    .map(f => {
      const base  = path.basename(f, path.extname(f));
      const mtime = fs.statSync(path.join(dir, f)).mtimeMs;
      const v     = `?v=${Math.floor(mtime)}`;
      if (path.extname(f).toLowerCase() === '.webm') {
        const posterFile = [...posterFiles].find(p => path.basename(p, path.extname(p)) === `${base}-poster`);
        if (posterFile) {
          const pmtime = fs.statSync(path.join(dir, posterFile)).mtimeMs;
          return { src: `images/${slug}/${f}${v}`, poster: `images/${slug}/${posterFile}?v=${Math.floor(pmtime)}` };
        }
        return { src: `images/${slug}/${f}${v}` };
      }
      return `images/${slug}/${f}${v}`;
    });

  manifest[slug] = items;
  console.log(`  ${slug}: ${items.length} item(s)`);
}

const output =
  `// Auto-generated by generate.js — do not edit manually\n` +
  `// Run "node generate.js" any time you add or remove images\n` +
  `const IMAGE_MANIFEST = ${JSON.stringify(manifest, null, 2)};\n`;

fs.writeFileSync('image-manifest.js', output);
console.log('\n✓ image-manifest.js updated');
